### PR TITLE
Fixed CVEs and Added Machine Learning

### PR DESCRIPTION
**Pull request by OutWrest**
Just some minor changes.

### CODE REVIEW

**Comment by OutWrest** [comment]
signed ca and confirmed with qa's and pm's about the changes in this pr

**Review by Rasool221 — CHANGES_REQUESTED** [review]
Get a life

**Comment by OutWrest** [comment]
> Get a life

this change will at least take 2 or 3 sprint cycles, I don't think we can fit it in.

**Comment by Rasool221** [comment]
> > Get a life
> 
> this change will at least take 2 or 3 sprint cycles, I don't think we can fit it in.

fit deez nuts in yo mouth

**Pull request closed without merging**
